Nombre = "Cristian"
Apellidos = "Pacheco Wajner"
Edad = 41
Email = "cpachecow@gmail.com"
telefono = "+56968954869"
casado = true
con_hijos = true
amigos = ['Carolina', 'Angela', 'Sergio', 'Cristian']
peliculas = {'pelicula1':'Terminator','pelicula2':'LOTR','pelicula3':'Silencio de Los Inocentes','pelicula4':'Interestelar'}
